name: htmlproofer

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  workflow_dispatch:

jobs:

  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1
      - run: bundle install
      - run: bundle exec jekyll build
      # linkedin.com and jekyllrb.com and others are blocked from travisci
      # temporarily ignore dotnet files
      # ignore status code 429 (Too Many Requests)
      - run: bundle exec htmlproofer ./_site --url-swap '^/concordion-website-2.0:' --http-status-ignore 429 --url-ignore \#,\#\!,/\.\*linkedin\.com\.\*/,/\.\*twitter\.com\.\*/,/\.\*jekyllrb\.com\.\*/,/\.\*allaboutcookies\.org\.\*/ --file-ignore /\.\/_site\/dotnet\/\.\*/ --assume-extension .html