name: htmlproofer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          arguments: '--url-swap ^/concordion-website-2.0: --url-ignore \#,\#\!,/\.\*linkedin\.com\.\*/,/\.\*twitter\.com\.\*/,/\.\*jekyllrb\.com\.\*/ --file-ignore /\.\/_site\/dotnet\/\.\*/ --assume-extension .html'